name: Nightly routine

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This pull request is stale for 2 weeks and is going to be closed'
          days-before-pr-stale: -1
          days-before-issue-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: -1
          stale-pr-label: 'stale'
          operations-per-run: 100
